dist: trusty
language: java
jdk:
  - oraclejdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn install
  - rm -rf $HOME/.m2/repository/dz/ummto/ansejNextGen
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

install: true

script:
- ./build.sh
